CONVERT_TO = rp2040_ce
USER_NAME := manna-harbour_miryoku

# OLED features
OLED_ENABLE = yes
OLED_DRIVER = ssd1306
WPM_ENABLE = yes
LTO_ENABLE = yes

VIA_ENABLE = yes

MIRYOKU_ALPHAS = QWERTY
MIRYOKU_TAP = QWERTY
MIRYOKU_LAYERS =