VIA_ENABLE = yes

CONVERT_TO = rp2040_ce

WPM_ENABLE = yes
LTO_ENABLE = yes
# RGBLIGHT_ENABLE = yes

OLED_ENABLE = yes
OLED_DRIVER = ssd1306

 CAPS_WORD_ENABLE = yes
 COMBO_SHOULD_TRIGGER = tes
 COMBO_ENABLE = yes

 TAP_DANCE_ENABLE = yes
