CONVERT_TO = rp2040_ce

# OLED and animation features
OLED_ENABLE = yes
OLED_DRIVER = ssd1306
WPM_ENABLE = yes
LTO_ENABLE = yes

VIA_ENABLE = yes

MIRYOKU_ALPHAS = QWERTY
MIRYOKU_TAP = QWERTY
MIRYOKU_LAYERS =
